---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-helm-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://bhagyeshsoni98.github.io/flux-custom-helm-chart

