---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-static-site
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux_chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
  interval: 1m0s

