apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-static-site
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
  values:
    image:
      repository: "bhagyesh19/static-site" # {"$imagepolicy": "flux-system:static-site-image-update-policy:name"}
      tag: "3.0.0" # {"$imagepolicy": "flux-system:static-site-image-update-policy:tag"}
  interval: 1m0s
