---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: static-site-image-update-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: static-site-image-repo
  policy:
    semver:
      range: '>=1.0.0'

