---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: static-site-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
      messageTemplate: Image updated to latest version
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: app-cluster
    strategy: Setters

